// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: storezhang/media/resolution.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分辨率
type Resolution int32

const (
	// 未知，不要使用
	Resolution_RESOLUTION_UNSPECIFIED Resolution = 0
	// 最低档，不要使用
	Resolution_P360 Resolution = 1
	// 标清
	Resolution_P480 Resolution = 2
	// 高清
	Resolution_P720 Resolution = 3
	// 超高清
	Resolution_P1080 Resolution = 4
	// 2K
	Resolution_K2 Resolution = 5
	// 4K
	Resolution_K4 Resolution = 6
	// 8K
	Resolution_K8 Resolution = 7
	// 音频
	Resolution_VOICE Resolution = 14
	// 原始分辨率
	Resolution_ORIGINAL Resolution = 15
	// 自定义分辨率
	// 尽量不使用自定义分辨率，也许相应的库并没有实现自定义分辨率功能
	Resolution_CUSTOMIZE Resolution = 127
)

// Enum value maps for Resolution.
var (
	Resolution_name = map[int32]string{
		0:   "RESOLUTION_UNSPECIFIED",
		1:   "P360",
		2:   "P480",
		3:   "P720",
		4:   "P1080",
		5:   "K2",
		6:   "K4",
		7:   "K8",
		14:  "VOICE",
		15:  "ORIGINAL",
		127: "CUSTOMIZE",
	}
	Resolution_value = map[string]int32{
		"RESOLUTION_UNSPECIFIED": 0,
		"P360":                   1,
		"P480":                   2,
		"P720":                   3,
		"P1080":                  4,
		"K2":                     5,
		"K4":                     6,
		"K8":                     7,
		"VOICE":                  14,
		"ORIGINAL":               15,
		"CUSTOMIZE":              127,
	}
)

func (x Resolution) Enum() *Resolution {
	p := new(Resolution)
	*p = x
	return p
}

func (x Resolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resolution) Descriptor() protoreflect.EnumDescriptor {
	return file_storezhang_media_resolution_proto_enumTypes[0].Descriptor()
}

func (Resolution) Type() protoreflect.EnumType {
	return &file_storezhang_media_resolution_proto_enumTypes[0]
}

func (x Resolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resolution.Descriptor instead.
func (Resolution) EnumDescriptor() ([]byte, []int) {
	return file_storezhang_media_resolution_proto_rawDescGZIP(), []int{0}
}

var File_storezhang_media_resolution_proto protoreflect.FileDescriptor

var file_storezhang_media_resolution_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2a, 0x91, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x55, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x33, 0x36, 0x30, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x34,
	0x38, 0x30, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x37, 0x32, 0x30, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x31, 0x30, 0x38, 0x30, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x32, 0x10,
	0x05, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x34, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x4b, 0x38, 0x10,
	0x07, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x0e, 0x12, 0x0c, 0x0a, 0x08,
	0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x41, 0x4c, 0x10, 0x0f, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x55,
	0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x10, 0x7f, 0x42, 0x3c, 0x0a, 0x15, 0x74, 0x65, 0x63,
	0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x3b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storezhang_media_resolution_proto_rawDescOnce sync.Once
	file_storezhang_media_resolution_proto_rawDescData = file_storezhang_media_resolution_proto_rawDesc
)

func file_storezhang_media_resolution_proto_rawDescGZIP() []byte {
	file_storezhang_media_resolution_proto_rawDescOnce.Do(func() {
		file_storezhang_media_resolution_proto_rawDescData = protoimpl.X.CompressGZIP(file_storezhang_media_resolution_proto_rawDescData)
	})
	return file_storezhang_media_resolution_proto_rawDescData
}

var file_storezhang_media_resolution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storezhang_media_resolution_proto_goTypes = []interface{}{
	(Resolution)(0), // 0: storezhang.media.Resolution
}
var file_storezhang_media_resolution_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storezhang_media_resolution_proto_init() }
func file_storezhang_media_resolution_proto_init() {
	if File_storezhang_media_resolution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storezhang_media_resolution_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storezhang_media_resolution_proto_goTypes,
		DependencyIndexes: file_storezhang_media_resolution_proto_depIdxs,
		EnumInfos:         file_storezhang_media_resolution_proto_enumTypes,
	}.Build()
	File_storezhang_media_resolution_proto = out.File
	file_storezhang_media_resolution_proto_rawDesc = nil
	file_storezhang_media_resolution_proto_goTypes = nil
	file_storezhang_media_resolution_proto_depIdxs = nil
}
